[package]
name = "light_probles_calculation"
version = "0.1.0"
authors = ["zigaosolin <ziga.osolin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spherical-harmonics = "0.1.0"
rand = "0.6.5"
